openapi: 3.2.0
info:
  title: HAProxy Data Plane Nameserver API
  description: 'API for editing and managing haproxy instances. Provides process information, configuration management,

    haproxy stats and logs.'
  version: '3.4'
  contact:
    name: HAProxy Support
    url: https://my.haproxy.com/portal/cust/login
    email: support@haproxy.com
servers:
- url: /v3
security:
- basic_auth: []
tags:
- name: Nameserver
paths:
  /services/haproxy/configuration/nameservers:
    get:
      description: Returns an array of all configured nameservers.
      operationId: getNameservers
      parameters:
      - description: Parent resolver name
        in: query
        name: resolver
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/transaction_id'
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameservers'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Return an array of nameservers
      tags:
      - Nameserver
    post:
      description: Adds a new nameserver to the resolvers section.
      operationId: createNameserver
      parameters:
      - description: Parent resolver name
        in: query
        name: resolver
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '201':
          description: Nameserver created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameserver'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameserver'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/AlreadyExists'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Add a nameserver
      tags:
      - Nameserver
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nameserver'
        required: true
  /services/haproxy/configuration/nameservers/{name}:
    delete:
      description: Deletes a nameserver from the resolvers section by it's name.
      operationId: deleteNameserver
      parameters:
      - description: Nameserver name
        in: path
        name: name
        required: true
        schema:
          type: string
      - description: Parent resolver name
        in: query
        name: resolver
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: Nameserver deleted
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Delete a nameserver
      tags:
      - Nameserver
    get:
      description: Returns one nameserver configuration by it's name.
      operationId: getNameserver
      parameters:
      - description: Nameserver name
        in: path
        name: name
        required: true
        schema:
          type: string
      - description: Parent resolver name
        in: query
        name: resolver
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/transaction_id'
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameserver'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Return a nameserver
      tags:
      - Nameserver
    put:
      description: Replaces a nameserver configuration by it's name.
      operationId: replaceNameserver
      parameters:
      - description: Nameserver name
        in: path
        name: name
        required: true
        schema:
          type: string
      - description: Parent resolver name
        in: query
        name: resolver
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '200':
          description: Nameserver replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameserver'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nameserver'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Replace a nameserver
      tags:
      - Nameserver
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/nameserver'
        required: true
components:
  parameters:
    transaction_id:
      name: transaction_id
      in: query
      description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
      required: false
      schema:
        type: string
    version:
      name: version
      in: query
      description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it's own version.
      required: false
      schema:
        type: integer
    force_reload:
      name: force_reload
      in: query
      description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
      required: false
      schema:
        type: boolean
        default: false
  schemas:
    error:
      additionalProperties:
        type: string
      description: API Error
      properties:
        code:
          type:
          - integer
          - 'null'
        message:
          type:
          - string
          - 'null'
      required:
      - code
      - message
      title: Error
      type: object
    nameservers:
      title: Nameservers
      description: Nameservers array
      type: array
      items:
        $ref: '#/components/schemas/nameserver'
    nameserver:
      description: Nameserver used in Runtime DNS configuration
      example:
        address: 10.0.0.1
        name: ns1
        port: 53
      properties:
        address:
          pattern: ^[^\s]+$
          type: string
        metadata:
          additionalProperties:
            type: object
        name:
          pattern: ^[A-Za-z0-9-_.:${}"]+$
          type: string
        port:
          maximum: 65535
          minimum: 1
          type:
          - integer
          - 'null'
      required:
      - name
      - address
      title: Nameserver
      type: object
  responses:
    DefaultError:
      description: General Error
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    NotFound:
      description: The specified resource was not found
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    BadRequest:
      description: Bad request
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    AlreadyExists:
      description: The specified resource already exists
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
externalDocs:
  url: https://docs.haproxy.org/
  description: HAProxy Documentation
