openapi: 3.2.0
info:
  title: HAProxy Data Plane Specification Openapiv3 API
  description: 'API for editing and managing haproxy instances. Provides process information, configuration management,

    haproxy stats and logs.'
  version: '3.4'
  contact:
    name: HAProxy Support
    url: https://my.haproxy.com/portal/cust/login
    email: support@haproxy.com
servers:
- url: /v3
security:
- basic_auth: []
tags:
- name: SpecificationOpenapiv3
paths:
  /specification_openapiv3:
    get:
      description: Return Data Plane API OpenAPI v3 specification
      operationId: getOpenapiv3Specification
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Data Plane API v3 Specification
      tags:
      - SpecificationOpenapiv3
components:
  schemas:
    error:
      additionalProperties:
        type: string
      description: API Error
      properties:
        code:
          type:
          - integer
          - 'null'
        message:
          type:
          - string
          - 'null'
      required:
      - code
      - message
      title: Error
      type: object
  responses:
    DefaultError:
      description: General Error
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
externalDocs:
  url: https://docs.haproxy.org/
  description: HAProxy Documentation
