openapi: 3.2.0
info:
  title: HAProxy Data Plane Stats API
  description: 'API for editing and managing haproxy instances. Provides process information, configuration management,

    haproxy stats and logs.'
  version: '3.4'
  contact:
    name: HAProxy Support
    url: https://my.haproxy.com/portal/cust/login
    email: support@haproxy.com
servers:
- url: /v3
security:
- basic_auth: []
tags:
- name: Stats
  description: Stats container
paths:
  /services/haproxy/stats/native:
    get:
      description: Getting stats from the HAProxy.
      operationId: getStats
      parameters:
      - description: Object type to get stats for (one of frontend, backend, server)
        in: query
        name: type
        required: false
        schema:
          type: string
          enum:
          - frontend
          - backend
          - server
      - description: Object name to get stats for
        in: query
        name: name
        required: false
        schema:
          type: string
      - description: Object parent name to get stats for, in case the object is a server
        in: query
        name: parent
        required: false
        x-dependency:
          query.type: server
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/native_stats'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/native_stats'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Gets stats
      tags:
      - Stats
components:
  schemas:
    error:
      additionalProperties:
        type: string
      description: API Error
      properties:
        code:
          type:
          - integer
          - 'null'
        message:
          type:
          - string
          - 'null'
      required:
      - code
      - message
      title: Error
      type: object
    native_stat:
      description: Current stats for one object.
      properties:
        backend_name:
          type: string
          x-dependency:
            type: server
        name:
          type: string
        stats:
          $ref: '#/components/schemas/native_stat_stats'
        type:
          enum:
          - backend
          - server
          - frontend
          type: string
      title: Stats
      type: object
    native_stat_stats:
      example:
        bin: 4326578
        bout: 889901290
        comp_byp: 0
        comp_in: 0
        comp_out: 0
        comp_rsp: 0
        conn_rate: 12
        conn_rate_max: 456
        conn_tot: 45682
        dcon: 0
        dreq: 4
        dresp: 1
        dses: 0
        ereq: 54
        hrsp_1xx: 0
        hrsp_2xx: 165
        hrsp_3xx: 12
        hrsp_4xx: 50
        hrsp_5xx: 4
        hrsp_other: 0
        iid: 0
        intercepted: 346
        last_chk: L4OK in 0ms
        mode: http
        pid: 3204
        rate: 64
        rate_lim: 20000
        rate_max: 4000
        req_rate: 49
        req_rate_max: 3965
        req_total: 1254786
        scur: 129
        slim: 2000
        smax: 2000
        status: UP
        stot: 12902
      properties:
        act:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        addr:
          type: string
          x-dependency:
            type: server
        agent_code:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        agent_desc:
          type: string
          x-dependency:
            type: server
        agent_duration:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        agent_fall:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        agent_health:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        agent_rise:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        agent_status:
          enum:
          - UNK
          - INI
          - SOCKERR
          - L4OK
          - L4TOUT
          - L4CON
          - L7OK
          - L7STS
          type: string
          x-dependency:
            type: server
        algo:
          type: string
          x-dependency:
            type: backend
        bck:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        bin:
          type:
          - integer
          - 'null'
        bout:
          type:
          - integer
          - 'null'
        check_code:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        check_desc:
          type: string
          x-dependency:
            type: server
        check_duration:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        check_fall:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        check_health:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        check_rise:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        check_status:
          enum:
          - UNK
          - INI
          - SOCKERR
          - L4OK
          - L4TOUT
          - L4CON
          - L6OK
          - L6TOUT
          - L6RSP
          - L7OK
          - L7OKC
          - L7TOUT
          - L7RSP
          - L7STS
          type: string
          x-dependency:
            type: server
        chkdown:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        chkfail:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        cli_abrt:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        comp_byp:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - frontend
            - backend
        comp_in:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - frontend
            - backend
        comp_out:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - frontend
            - backend
        comp_rsp:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - frontend
            - backend
        conn_rate:
          type:
          - integer
          - 'null'
          x-dependency:
            type: frontend
        conn_rate_max:
          type:
          - integer
          - 'null'
          x-dependency:
            type: frontend
        conn_tot:
          type:
          - integer
          - 'null'
          x-dependency:
            type: frontend
        cookie:
          type: string
          x-dependency:
            type:
            - server
            - backend
        ctime:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        dcon:
          type:
          - integer
          - 'null'
          x-dependency:
            type: frontend
        downtime:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        dreq:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - frontend
            - backend
        dresp:
          type:
          - integer
          - 'null'
        dses:
          type:
          - integer
          - 'null'
          x-dependency:
            type: frontend
        econ:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        ereq:
          type:
          - integer
          - 'null'
          x-dependency:
            type: frontend
        eresp:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        hanafail:
          type: string
          x-dependency:
            type: server
        hrsp_1xx:
          type:
          - integer
          - 'null'
        hrsp_2xx:
          type:
          - integer
          - 'null'
        hrsp_3xx:
          type:
          - integer
          - 'null'
        hrsp_4xx:
          type:
          - integer
          - 'null'
        hrsp_5xx:
          type:
          - integer
          - 'null'
        hrsp_other:
          type:
          - integer
          - 'null'
        iid:
          type:
          - integer
          - 'null'
        intercepted:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - frontend
            - backend
        last_agt:
          type:
          - string
          - 'null'
          x-dependency:
            type: server
        last_chk:
          type:
          - string
          - 'null'
          x-dependency:
            type: server
        lastchg:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        lastsess:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        lbtot:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        mode:
          enum:
          - tcp
          - http
          - health
          - unknown
          type: string
        pid:
          type:
          - integer
          - 'null'
        qcur:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        qlimit:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        qmax:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        qtime:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        rate:
          type:
          - integer
          - 'null'
        rate_lim:
          type:
          - integer
          - 'null'
          x-dependency:
            type: frontend
        rate_max:
          type:
          - integer
          - 'null'
        req_rate:
          type:
          - integer
          - 'null'
          x-dependency:
            type: frontend
        req_rate_max:
          type:
          - integer
          - 'null'
          x-dependency:
            type: frontend
        req_tot:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - frontend
            - backend
        rtime:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        scur:
          type:
          - integer
          - 'null'
        sid:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        slim:
          type:
          - integer
          - 'null'
        smax:
          type:
          - integer
          - 'null'
        srv_abrt:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        status:
          enum:
          - UP
          - DOWN
          - NOLB
          - MAINT
          - no check
          type: string
        stot:
          type:
          - integer
          - 'null'
        throttle:
          type:
          - integer
          - 'null'
          x-dependency:
            type: server
        tracked:
          type: string
          x-dependency:
            type: server
        ttime:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        weight:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        wredis:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
        wretr:
          type:
          - integer
          - 'null'
          x-dependency:
            type:
            - server
            - backend
      type: object
    native_stats:
      description: HAProxy stats array
      properties:
        error:
          type: string
        runtimeAPI:
          type: string
        stats:
          items:
            $ref: '#/components/schemas/native_stat'
          type: array
          x-omitempty: true
      title: Stats Array
      type: object
      x-omitempty: true
  responses:
    DefaultError:
      description: General Error
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
externalDocs:
  url: https://docs.haproxy.org/
  description: HAProxy Documentation
