openapi: 3.2.0
info:
  title: HAProxy Data Plane Dgram Bind API
  description: 'API for editing and managing haproxy instances. Provides process information, configuration management,

    haproxy stats and logs.'
  version: '3.4'
  contact:
    name: HAProxy Support
    url: https://my.haproxy.com/portal/cust/login
    email: support@haproxy.com
servers:
- url: /v3
security:
- basic_auth: []
tags:
- name: DgramBind
paths:
  /services/haproxy/configuration/log_forwards/{parent_name}/dgram_binds:
    get:
      description: Returns an array of all dgram binds that are configured in specified log forward.
      operationId: getDgramBinds
      parameters:
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_binds'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Return an array of dgram binds
      tags:
      - DgramBind
    post:
      description: Adds a new dgram bind in the specified log forward in the configuration file.
      operationId: createDgramBind
      parameters:
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '201':
          description: Bind created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_bind'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_bind'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/AlreadyExists'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Add a new dgram bind
      tags:
      - DgramBind
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dgram_bind'
        required: true
  /services/haproxy/configuration/log_forwards/{parent_name}/dgram_binds/{name}:
    delete:
      description: Deletes a dgram bind configuration by it's name in the specified log forward.
      operationId: deleteDgramBind
      parameters:
      - description: Bind name
        in: path
        name: name
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: Bind deleted
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Delete a dgram bind
      tags:
      - DgramBind
    get:
      description: Returns one dgram bind configuration by it's name in the specified log forward.
      operationId: getDgramBind
      parameters:
      - description: Bind name
        in: path
        name: name
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_bind'
        '404':
          $ref: '#/components/responses/AlreadyExists'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Return one dgram bind
      tags:
      - DgramBind
    put:
      description: Replaces a dgram bind configuration by it's name in the specified log forward.
      operationId: replaceDgramBind
      parameters:
      - description: Bind name
        in: path
        name: name
        required: true
        schema:
          type: string
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '200':
          description: Bind replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_bind'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dgram_bind'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Replace a dgram bind
      tags:
      - DgramBind
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dgram_bind'
        required: true
components:
  parameters:
    transaction_id:
      name: transaction_id
      in: query
      description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
      required: false
      schema:
        type: string
    version:
      name: version
      in: query
      description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it's own version.
      required: false
      schema:
        type: integer
    parent_name:
      name: parent_name
      in: path
      description: Parent name
      required: true
      schema:
        type: string
        pattern: ^[^\r\n<>*;$#&{}"]+$
    force_reload:
      name: force_reload
      in: query
      description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
      required: false
      schema:
        type: boolean
        default: false
  schemas:
    error:
      additionalProperties:
        type: string
      description: API Error
      properties:
        code:
          type:
          - integer
          - 'null'
        message:
          type:
          - string
          - 'null'
      required:
      - code
      - message
      title: Error
      type: object
    dgram_bind:
      description: HAProxy log forward dgram bind configuration
      properties:
        address:
          pattern: ^[^\s]+$
          type: string
        interface:
          type: string
        metadata:
          additionalProperties:
            type: object
        name:
          pattern: ^[^\s]+$
          type: string
        namespace:
          type: string
        port:
          maximum: 65535
          minimum: 1
          type:
          - integer
          - 'null'
        port-range-end:
          maximum: 65535
          minimum: 1
          type:
          - integer
          - 'null'
        transparent:
          type: boolean
      required:
      - name
      title: Dgram Bind
      type: object
    dgram_binds:
      title: Dgram Bind
      description: HAProxy dgram bind array
      type: array
      items:
        $ref: '#/components/schemas/dgram_bind'
  responses:
    DefaultError:
      description: General Error
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    NotFound:
      description: The specified resource was not found
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    BadRequest:
      description: Bad request
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    AlreadyExists:
      description: The specified resource already exists
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
externalDocs:
  url: https://docs.haproxy.org/
  description: HAProxy Documentation
