openapi: 3.2.0
info:
  title: HAProxy Data Plane QUIC Initial Rule API
  description: 'API for editing and managing haproxy instances. Provides process information, configuration management,

    haproxy stats and logs.'
  version: '3.4'
  contact:
    name: HAProxy Support
    url: https://my.haproxy.com/portal/cust/login
    email: support@haproxy.com
servers:
- url: /v3
security:
- basic_auth: []
tags:
- name: QUICInitialRule
paths:
  /services/haproxy/configuration/frontends/{parent_name}/quic_initial_rules:
    get:
      description: Returns all QUIC Initial rules that are configured in specified parent.
      operationId: getAllQUICInitialRuleFrontend
      parameters:
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rules'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Return an array of all QUIC Initial rules
      tags:
      - QUICInitialRule
    put:
      description: Replaces a whole list of QUIC Initial rules with the list given in parameter
      operationId: replaceAllQUICInitialRuleFrontend
      parameters:
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '200':
          description: All TTP After Response Rules lines replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rules'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rules'
        '400':
          $ref: '#/components/responses/BadRequest'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Replace an QUIC Initial rules list
      tags:
      - QUICInitialRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quic_initial_rules'
        required: true
  /services/haproxy/configuration/defaults/{parent_name}/quic_initial_rules:
    get:
      description: Returns all QUIC Initial rules that are configured in specified parent.
      operationId: getAllQUICInitialRuleDefaults
      parameters:
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rules'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Return an array of all QUIC Initial rules
      tags:
      - QUICInitialRule
    put:
      description: Replaces a whole list of QUIC Initial rules with the list given in parameter
      operationId: replaceAllQUICInitialRuleDefaults
      parameters:
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '200':
          description: All TTP After Response Rules lines replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rules'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rules'
        '400':
          $ref: '#/components/responses/BadRequest'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Replace an QUIC Initial rules list
      tags:
      - QUICInitialRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quic_initial_rules'
        required: true
  /services/haproxy/configuration/frontends/{parent_name}/quic_initial_rules/{index}:
    delete:
      description: Deletes a QUIC Initial Rule configuration by it's index from the specified parent.
      operationId: deleteQUICInitialRuleFrontend
      parameters:
      - description: QUIC Initial Rule Index
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: QUIC Initial Rule deleted
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Delete a QUIC Initial Rule
      tags:
      - QUICInitialRule
    get:
      description: Returns one QUIC Initial Rule configuration by it's index in the specified parent.
      operationId: getQUICInitialRuleFrontend
      parameters:
      - description: QUIC Initial Rule Index
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Return one QUIC Initial Rule
      tags:
      - QUICInitialRule
    post:
      description: Adds a new QUIC Initial Rule of the specified type in the specified parent.
      operationId: createQUICInitialRuleFrontend
      parameters:
      - description: QUIC Initial Rule Index
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '201':
          description: HTTP Response Rule created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/AlreadyExists'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Add a new QUIC Initial Rule
      tags:
      - QUICInitialRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quic_initial_rule'
        required: true
    put:
      description: Replaces a QUIC Initial Rule configuration by it's index in the specified parent.
      operationId: replaceQUICInitialRuleFrontend
      parameters:
      - description: QUIC Initial Rule Index
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '200':
          description: QUIC Initial Rule replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Replace a QUIC Initial Rule
      tags:
      - QUICInitialRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quic_initial_rule'
        required: true
  /services/haproxy/configuration/defaults/{parent_name}/quic_initial_rules/{index}:
    delete:
      description: Deletes a QUIC Initial Rule configuration by it's index from the specified parent.
      operationId: deleteQUICInitialRuleDefaults
      parameters:
      - description: QUIC Initial Rule Index
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: QUIC Initial Rule deleted
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Delete a QUIC Initial Rule
      tags:
      - QUICInitialRule
    get:
      description: Returns one QUIC Initial Rule configuration by it's index in the specified parent.
      operationId: getQUICInitialRuleDefaults
      parameters:
      - description: QUIC Initial Rule Index
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Return one QUIC Initial Rule
      tags:
      - QUICInitialRule
    post:
      description: Adds a new QUIC Initial Rule of the specified type in the specified parent.
      operationId: createQUICInitialRuleDefaults
      parameters:
      - description: QUIC Initial Rule Index
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '201':
          description: HTTP Response Rule created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/AlreadyExists'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Add a new QUIC Initial Rule
      tags:
      - QUICInitialRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quic_initial_rule'
        required: true
    put:
      description: Replaces a QUIC Initial Rule configuration by it's index in the specified parent.
      operationId: replaceQUICInitialRuleDefaults
      parameters:
      - description: QUIC Initial Rule Index
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '200':
          description: QUIC Initial Rule replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quic_initial_rule'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Replace a QUIC Initial Rule
      tags:
      - QUICInitialRule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quic_initial_rule'
        required: true
components:
  parameters:
    transaction_id:
      name: transaction_id
      in: query
      description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
      required: false
      schema:
        type: string
    version:
      name: version
      in: query
      description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it's own version.
      required: false
      schema:
        type: integer
    parent_name:
      name: parent_name
      in: path
      description: Parent name
      required: true
      schema:
        type: string
        pattern: ^[^\r\n<>*;$#&{}"]+$
    force_reload:
      name: force_reload
      in: query
      description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
      required: false
      schema:
        type: boolean
        default: false
  schemas:
    error:
      additionalProperties:
        type: string
      description: API Error
      properties:
        code:
          type:
          - integer
          - 'null'
        message:
          type:
          - string
          - 'null'
      required:
      - code
      - message
      title: Error
      type: object
    quic_initial_rule:
      additionalProperties: false
      description: QUIC Initial configuration
      example:
        type: reject
      properties:
        cond:
          enum:
          - if
          - unless
          type: string
          x-display-name: Condition
        cond_test:
          type: string
          x-dependency:
            cond:
              required: true
          x-display-name: Condition Test
          x-dynamic-enum:
            freeFormat: true
            operation: getACLs
            property: acl_name
        metadata:
          additionalProperties:
            type: object
        type:
          enum:
          - reject
          - accept
          - send-retry
          - dgram-drop
          type: string
      required:
      - type
      title: QUIC Initial
      type: object
      x-go-name: QUICInitialRule
    quic_initial_rules:
      title: QUIC Initials Array
      x-go-name: QUICInitialRules
      type: array
      items:
        $ref: '#/components/schemas/quic_initial_rule'
  responses:
    DefaultError:
      description: General Error
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    NotFound:
      description: The specified resource was not found
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    BadRequest:
      description: Bad request
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    AlreadyExists:
      description: The specified resource already exists
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
externalDocs:
  url: https://docs.haproxy.org/
  description: HAProxy Documentation
