openapi: 3.2.0
info:
  title: HAProxy Data Plane SSL Front Use API
  description: 'API for editing and managing haproxy instances. Provides process information, configuration management,

    haproxy stats and logs.'
  version: '3.4'
  contact:
    name: HAProxy Support
    url: https://my.haproxy.com/portal/cust/login
    email: support@haproxy.com
servers:
- url: /v3
security:
- basic_auth: []
tags:
- name: SSLFrontUse
paths:
  /services/haproxy/configuration/frontends/{parent_name}/ssl_front_uses:
    get:
      description: Returns an array of all SSLFrontUses that are configured in specified frontend.
      operationId: getAllSSLFrontUses
      parameters:
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ssl_front_uses'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Return an array of SSLFrontUses
      tags:
      - SSLFrontUse
    post:
      description: Adds a new SSLFrontUse in the specified frontend in the configuration file.
      operationId: createSSLFrontUse
      parameters:
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '201':
          description: SSLFrontUse created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ssl_front_use'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ssl_front_use'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/AlreadyExists'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Add a new SSLFrontUse
      tags:
      - SSLFrontUse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ssl_front_use'
        required: true
  /services/haproxy/configuration/frontends/{parent_name}/ssl_front_uses/{index}:
    delete:
      description: Deletes an SSLFrontUse configuration by its index in the specified frontend.
      operationId: deleteSSLFrontUse
      parameters:
      - description: SSLFrontUse index (zero-based)
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
        '204':
          description: SSLFrontUse deleted
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Delete an SSLFrontUse
      tags:
      - SSLFrontUse
    get:
      description: Returns one SSLFrontUse configuration by its index in the specified frontend.
      operationId: getSSLFrontUse
      parameters:
      - description: SSLFrontUse index (zero-based)
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      responses:
        '200':
          description: Successful operation
          headers:
            Configuration-Version:
              description: Configuration file version
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ssl_front_use'
        '404':
          $ref: '#/components/responses/AlreadyExists'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Return one SSLFrontUse
      tags:
      - SSLFrontUse
    put:
      description: Replaces an SSLFrontUse configuration by its index in the specified frontend.
      operationId: replaceSSLFrontUse
      parameters:
      - description: SSLFrontUse index (zero-based)
        in: path
        name: index
        required: true
        schema:
          type: integer
      - $ref: '#/components/parameters/parent_name'
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/version'
      - $ref: '#/components/parameters/force_reload'
      responses:
        '200':
          description: SSLFrontUse replaced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ssl_front_use'
        '202':
          description: Configuration change accepted and reload requested
          headers:
            Reload-ID:
              description: ID of the requested reload
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ssl_front_use'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Replace an SSLFrontUse
      tags:
      - SSLFrontUse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ssl_front_use'
        required: true
components:
  schemas:
    ssl_front_uses:
      type: array
      items:
        $ref: '#/components/schemas/ssl_front_use'
      x-omitempty: true
      x-go-name: SSLFrontUses
    error:
      additionalProperties:
        type: string
      description: API Error
      properties:
        code:
          type:
          - integer
          - 'null'
        message:
          type:
          - string
          - 'null'
      required:
      - code
      - message
      title: Error
      type: object
    ssl_front_use:
      description: Assign a certificate to the current frontend
      properties:
        allow_0rtt:
          type: boolean
        alpn:
          type: string
          x-display-name: ALPN Protocols
        ca_file:
          type: string
        certificate:
          description: Certificate filename
          pattern: ^[^\s]+$
          type: string
        ciphers:
          type: string
        ciphersuites:
          type: string
        client_sigalgs:
          type: string
        crl_file:
          type: string
        curves:
          type: string
        ecdhe:
          type: string
        issuer:
          description: OCSP issuer filename
          type: string
        key:
          description: Private key filename
          type: string
        metadata:
          additionalProperties:
            type: object
        no_alpn:
          type: boolean
        no_ca_names:
          type: boolean
        npn:
          type: string
        ocsp:
          description: OCSP response filename
          type: string
        ocsp_update:
          description: Automatic OCSP response update
          enum:
          - enabled
          - disabled
          type: string
        sctl:
          description: Signed Certificate Timestamp List filename
          type: string
        sigalgs:
          type: string
        ssl_max_ver:
          enum:
          - SSLv3
          - TLSv1.0
          - TLSv1.1
          - TLSv1.2
          - TLSv1.3
          type: string
        ssl_min_ver:
          enum:
          - SSLv3
          - TLSv1.0
          - TLSv1.1
          - TLSv1.2
          - TLSv1.3
          type: string
        verify:
          enum:
          - none
          - optional
          - required
          type: string
      required:
      - certificate
      title: SSL Frontend Use certificate
      type: object
      x-go-name: SSLFrontUse
  parameters:
    transaction_id:
      name: transaction_id
      in: query
      description: ID of the transaction where we want to add the operation. Cannot be used when version is specified.
      required: false
      schema:
        type: string
    version:
      name: version
      in: query
      description: Version used for checking configuration version. Cannot be used when transaction is specified, transaction has it's own version.
      required: false
      schema:
        type: integer
    parent_name:
      name: parent_name
      in: path
      description: Parent name
      required: true
      schema:
        type: string
        pattern: ^[^\r\n<>*;$#&{}"]+$
    force_reload:
      name: force_reload
      in: query
      description: If set, do a force reload, do not wait for the configured reload-delay. Cannot be used when transaction is specified, as changes in transaction are not applied directly to configuration.
      required: false
      schema:
        type: boolean
        default: false
  responses:
    DefaultError:
      description: General Error
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    NotFound:
      description: The specified resource was not found
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    BadRequest:
      description: Bad request
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    AlreadyExists:
      description: The specified resource already exists
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
externalDocs:
  url: https://docs.haproxy.org/
  description: HAProxy Documentation
