openapi: 3.2.0
info:
  title: HAProxy Data Plane Acme Runtime API
  description: 'API for editing and managing haproxy instances. Provides process information, configuration management,

    haproxy stats and logs.'
  version: '3.4'
  contact:
    name: HAProxy Support
    url: https://my.haproxy.com/portal/cust/login
    email: support@haproxy.com
servers:
- url: /v3
security:
- basic_auth: []
tags:
- name: AcmeRuntime
paths:
  /services/haproxy/runtime/acme:
    get:
      description: Returns the status of each managed ACME certificate.
      operationId: getAcmeStatus
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/acme_status'
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: ACME Status
      tags:
      - AcmeRuntime
    put:
      description: Force renewal of an ACME certificate.
      operationId: renewAcmeCertificate
      parameters:
      - description: Certificate file name
        in: query
        name: certificate
        required: true
        schema:
          type: string
          pattern: ^[^\r\n<>*;$#&{}"]+$
      responses:
        '200':
          description: Operation started
        '404':
          $ref: '#/components/responses/NotFound'
        default:
          $ref: '#/components/responses/DefaultError'
      summary: Renew ACME certificate
      tags:
      - AcmeRuntime
components:
  schemas:
    error:
      additionalProperties:
        type: string
      description: API Error
      properties:
        code:
          type:
          - integer
          - 'null'
        message:
          type:
          - string
          - 'null'
      required:
      - code
      - message
      title: Error
      type: object
    acme_certificate_status:
      description: Status of a single ACME certificate from runtime.
      properties:
        acme_section:
          description: ACME section which generated the certificate.
          type: string
        certificate:
          description: Certificate name
          type: string
        expiries_in:
          description: Duration until certificate expiry.
          type: string
        expiry_date:
          description: Certificate expiration date.
          format: date-time
          type: string
        renewal_in:
          description: Duration until the next planned renewal.
          type: string
        scheduled_renewal:
          description: Planned date for certificate renewal.
          format: date-time
          type: string
        state:
          description: State of the ACME task, either "Running" or "Scheduled".
          type: string
      title: ACME certificate status
      type: object
    acme_status:
      title: ACME status
      description: Status of all the ACME certificates from runtime.
      type: array
      items:
        $ref: '#/components/schemas/acme_certificate_status'
  responses:
    DefaultError:
      description: General Error
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    NotFound:
      description: The specified resource was not found
      headers:
        Configuration-Version:
          description: Configuration file version
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
externalDocs:
  url: https://docs.haproxy.org/
  description: HAProxy Documentation
